name: automergedependabot

on: [pull_request_target]
  workflow_dispatch:

jobs:
  auto-merge:

    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v2
      
      - name: 'Automerge dependency updates from Dependabot'
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
